apiVersion: v1
kind: Service
metadata:
  name: apollo-adminservice
  namespace: gw-middleware
  labels:
    app: apollo-adminservice
spec:
  ports:
    - port: 8090
      targetPort: 8090
      name: http
  selector:
    app: apollo-adminservice
